apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: devops
  labels:
    app: busybox
spec:
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 5
>>>>>>> 495b2ab0fb37ffc31c41de3e6eec6c8bc7b252c3
  selector:
    matchLabels:
      app: busybox  # POD label과 일치
  template:
    metadata:
      labels:
        app: busybox # Selector label과 일치
    spec:
      containers:
      - name: busybox
        #image: busybox
        image: harbor.myweb.io/erp/busybox:0.1
        command:
        - "/bin/sh"
        - "-c"
        - "sleep inf"
